- to:
   mean: 0.05
   std: 0.05
- auxpass:
   mean: 0.03
   std: 0.03
- adj_infl:
   mean: 0.05
   std: 0.05
- noun_infl:
   mean: 0.05
   std: 0.05
- verb_infl:
   mean: 0.1
   std: 0.1
   aux_ratio: 0.20
- del:
   mean: 0.01
   std: 0.01
- mask:
   mean: 0.15
   std: 0.15
   p: 0.8
   threshold_mean: 0.20
   threshold_std: 0.20

